import { useEffect, useRef } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { BiMenu } from "react-icons/bi";
import { GiAnimalSkull } from "react-icons/gi";

import anime from "animejs";
import Desktop from "../components/templates/Desktop";
import NavItem from "../components/templates/Desktop/Menu";
import dynamic from "next/dynamic";
const Sketch = dynamic(() => import("../components/templates/Sketch"), {
  ssr: false,
});

const Home: NextPage = () => {
  const element = useRef<HTMLHeadingElement>(null);

  useEffect(() => {
    if (!!element.current) {
      const tl = anime.timeline({
        duration: 3000,
        easing: "easeOutExpo",
      });

      tl.add({
        targets: ".clear-initial",
        opacity: 1,
        translateY: {
          value: [-100, 0],
          duration: 800,
        },
      });

      tl.add(
        {
          targets: ".wrapper-presentation",
          height: 50,
          width: 50,
          left: "50%",
          top: "50%",
          // opacity: 0,
          color: "#FFF",
          backgroundColor: "#FFF",
          borderRadius: 360,
          duration: 1000,
        },
        "+=800"
      );

      tl.add({
        targets: ".wrapper-presentation",
        translateY: -2000,
        opacity: 0,
        easing: "easeOutElastic(1, .8)",
        loop: true,
      });
    }
  }, [element]);

  return (
    <div ref={element}>
      <Head>
        <title>Pagina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="wrapper-presentation">
          <h1 className="clear-initial">Welcome</h1>
        </div>
        <nav>
          <h3>Landing Page</h3>
          <a href="#" className="left-auto">
            About me
          </a>
          <a href="#">Works</a>
          <a href="#">Blog</a>
        </nav>
        <div className="main-container">
          <Sketch variant="flow" customClass="p-0" />
          <div className="blured"></div>
          <div className="wrapper-content">
            <div className="row">
              <div className="column">
                <h1>Jorge Felix</h1>
                <h2>Frontend Developer</h2>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
